from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.auth.domain.models import AccessToken, User, UserCreateData, UserUpdateData


class AuthRepository(Protocol):
    def get_user_by_email(self, email: str) -> User | None: ...

    def get_user_by_id(self, user_id: UUID) -> User | None: ...

    def list_users(self, skip: int, limit: int) -> list[User]: ...

    def create_user(self, data: UserCreateData, hashed_password: str | None) -> User: ...

    def update_user(self, user_id: UUID, updates: UserUpdateData) -> User | None: ...

    def delete_user(self, user_id: UUID) -> bool: ...

    def create_token(self, user_id: UUID, token: str, expires_at: datetime) -> AccessToken: ...

    def list_tokens(self, skip: int, limit: int) -> list[AccessToken]: ...

    def get_token_by_id(self, token_id: UUID) -> AccessToken | None: ...

    def find_active_token(self, token: str, current_time: datetime) -> AccessToken | None: ...

    def deactivate_token(self, token_id: UUID) -> bool: ...

    def delete_token(self, token_id: UUID) -> bool: ...
