from datetime import datetime
from typing import Generic, Protocol, TypeVar
from uuid import UUID

from app.auth.domain.models import AccessToken, User, UserCreateData, UserUpdateData

DB = TypeVar("DB")


class AuthRepository(Protocol, Generic[DB]):
    def get_user_by_email(self, db: DB, email: str) -> User | None: ...

    def get_user_by_id(self, db: DB, user_id: UUID) -> User | None: ...

    def list_users(self, db: DB, skip: int, limit: int) -> list[User]: ...

    def create_user(self, db: DB, data: UserCreateData, hashed_password: str | None) -> User: ...

    def update_user(self, db: DB, user_id: UUID, updates: UserUpdateData) -> User | None: ...

    def delete_user(self, db: DB, user_id: UUID) -> bool: ...

    def create_token(self, db: DB, user_id: UUID, token: str, expires_at: datetime) -> AccessToken: ...

    def list_tokens(self, db: DB, skip: int, limit: int) -> list[AccessToken]: ...

    def get_token_by_id(self, db: DB, token_id: UUID) -> AccessToken | None: ...

    def find_active_token(self, db: DB, token: str, current_time: datetime) -> AccessToken | None: ...

    def deactivate_token(self, db: DB, token_id: UUID) -> bool: ...

    def delete_token(self, db: DB, token_id: UUID) -> bool: ...
