from datetime import datetime

from app.minigame.domain.model.guess_number import GuessNumberGame
from app.minigame.domain.model.rps import RPSGame
from app.minigame.domain.model.word_guess import WordGuessGame


class MinigameRepository:
    def set_stream_start_time(self, channel_name: str, start_time: datetime): ...

    def reset_stream_state(self, channel_name: str): ...

    def get_last_game_time(self, channel_name: str) -> datetime | None: ...

    def get_stream_start_time(self, channel_name: str) -> datetime | None: ...

    def save_active_guess_number_game(self, channel_name: str, game: GuessNumberGame): ...

    def delete_guess_number_game(self, channel_name: str): ...

    def delete_guess_game(self, channel_name: str): ...

    def get_active_rps_game(self, channel_name: str) -> RPSGame | None: ...

    def get_active_guess_game(self, channel_name: str) -> GuessNumberGame | None: ...

    def get_active_word_game(self, channel_name: str) -> WordGuessGame | None: ...

    def save_word_gues_game(self, channel_name: str, game: WordGuessGame): ...

    def delete_word_guess_game(self, channel_name: str): ...

    def finish_word_game_timeout(self, channel_name: str) -> str: ...

    def save_active_rps_game(self, channel_name: str, game: RPSGame): ...

    def finish_rps(self, game: RPSGame, channel_name: str) -> tuple[str, str, list[str]]: ...
