from __future__ import annotations

from typing import Protocol

from app.commands.chat.chat_event_handler import ChatEventHandler
from core.chat.interfaces import ChatContext, CommandRouter


class ChatOutbound(Protocol):
    def set_router(self, router: CommandRouter) -> None: ...
    def set_chat_event_handler(self, handler: ChatEventHandler) -> None: ...
    async def send_channel_message(self, channel_name: str, message: str) -> None: ...
    async def post_message(self, message: str, chat_ctx: ChatContext) -> None: ...
