from __future__ import annotations

from typing import Protocol

from core.chat.interfaces import CommandRouter


class ChatEventsHandler(Protocol):
    async def handle(self, *, channel_name: str, display_name: str, message: str, bot_name: str) -> None: ...


class ChatOutbound(Protocol):
    def set_router(self, router: CommandRouter) -> None: ...
    def set_chat_event_handler(self, handler: ChatEventsHandler) -> None: ...
    async def send_channel_message(self, message: str) -> None: ...
    async def post_message(self, message: str) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
